### PR TITLE
Updated link to firebase conguration guide

### LINKED ISSUE #104: Update README.md (google-services documentation)
I guess the `FCM Firebase Cloud Messaging` secton in the README.md is outdated. Google-services.json directory is wrong according to the new project structure.

### PR DESCRIPTION
**Pull request by estefi-prieto**
This PR provides:
an updated link to firebase configuration guide

Closes #104

### CODE REVIEW

**Review by sgobotta — CHANGES_REQUESTED** [review]
Why is it linking to a guide in Spanish? I guess we don't have one in English, do we?

**Comment by estefi-prieto** [comment]
Because we don't have one guide to configure firebase in English.

**Comment by sgobotta** [comment]
Ok, I've opened an issue

We can either work on #117 and fix the link or remove the link and link it when 117 is done.

**Comment by sgobotta** [comment]
#117 is ready to be merged, this issue is blocked no more. All we need to do is update the link url

**Review by sgobotta — APPROVED** [review]

**Pull request merged**
