### PR TITLE
Initial translation of config guide to Portuguese

### PR DESCRIPTION
**Pull request by lays147**
This fit the #3 However I wasn't able to build the app because I can't clone the git link provided on the src code, and with the code on GitHub don't appear to be the same from the screenshots of the Spanish translation. 
So I used Portuguese screenshots where I was able to, and use the Spanish ones on the parts that I wasn't able to create screenshots. 

Signed-off-by: Lays Rodrigues <lays.silva@tvglobo.com.br>

### CODE REVIEW

**Comment by FacundoMainere** [comment]
Just two things:
- Can you use the same name standard for the files that we used in the spanish docs? e.g: Firebase-configuration-guide_pt.md 
- The 20th image has a broken link 

Thank you!

**Comment by lays147** [comment]
Branch updated:
Rebase to develop
+ @FacundoMainere requests

**Comment by FacundoMainere** [comment]
Good job! thank you very much.

**Comment by lays147** [comment]
@FacundoMainere Thank you!

**Pull request merged**
