### PR TITLE
Adds documentation for the input file format

### LINKED ISSUE #106: Create ns-vue-radio tool: input file design
Subtask of #105 

Define a proper structure for the input file containing customizations.

This `input file`~/json response~ will contain attributes that will be read and eventually used to generate/populate a config.js file. ~We'll need to write a simple adapter that helps the script read and use the data, this issues will help us understand the structure of this data.~

Why we need this file design?
Because:
1.  ~Data is obtained from an API~ Data is obtained from a file, then passed to the vue-ns application
2.   ~An adapter interprets this data and makes it available in a form that other software parts understand~

~Therefore we need to know how to parse data in this adapter.~

Data will be passed to the application through bash env variables and consumed during the webpack process

### LINKED ISSUE #118: Config.js create documentation
Create documentation for the Config.js file containing:

`attribute`: `type` - `description of the attribute (what is it used for)

Update README.md with a link to this new file.

### PR DESCRIPTION
**Pull request by sgobotta**
This PR provides:

+   documentation for the input file format

Closes #106
Closes #118

### CODE REVIEW

**Comment by estefi-prieto** [comment]
Tool can read a `section` field from the input file too.

```
### sections

   **Details:** An array with the application sections.  The sections can be "Live", "Schedule", "WriteUs", "Podcasts", "Social" .
   **Type:** `Array`
```

**Comment by sgobotta** [comment]
> Tool can read a `section` field from the input file too.
> 
> ```
> ### sections
> 
>    **Details:** An array with the application sections.  The sections can be "Live", "Schedule", "WriteUs", "Podcasts", "Social" .
>    **Type:** `Array`
> ```

Great, add it to the docs please!

**Comment by estefi-prieto** [comment]
> > Tool can read a `section` field from the input file too.
> > ```
> > ### sections
> > 
> >    **Details:** An array with the application sections.  The sections can be "Live", "Schedule", "WriteUs", "Podcasts", "Social" .
> >    **Type:** `Array`
> > ```
> 
> Great, add it to the docs please!

Don't worry

**Comment by sgobotta** [comment]
> > > Tool can read a `section` field from the input file too.
> > > ```
> > > ### sections
> > > 
> > >    **Details:** An array with the application sections.  The sections can be "Live", "Schedule", "WriteUs", "Podcasts", "Social" .
> > >    **Type:** `Array`
> > > ```
> > 
> > 
> > Great, add it to the docs please!
> 
> Don't worry

You have to approve it : )

**Review by estefi-prieto — APPROVED** [review]

**Pull request merged**
